from enum import StrEnum


class RawJobColumns(StrEnum):
    TITLE = "title"
    COMPANY_NAME = "company_name"
    DESCRIPTION = "description"
    LOCATION = "location"
    DATE_POSTED = "date_posted"
    URL = "url"


MAX_ITEMS_TO_SCRAPE = 10

# Websites to scrape
WORKUA_URL = "https://work.ua/jobs-python/"
RABOTAUA_URL = "https://rabota.ua/zapros/python"
DOUUA_URL = "https://jobs.dou.ua/vacancies/?category=Python"

# Output scraping file path
SCRAPING_OUTPUT_FILE = "scraping/data/jobs.csv"

# Output analysis file path
ANALYSIS_OUTPUT_FILE = "analytics/data/tech_counts.csv"

TECHNOLOGIES_TO_ANALYZE = {
    "python": ["python"],
    "django": ["django"],
    "flask": ["flask"],
    "aws": ["aws", "amazon web services"],
    "kubernetes": ["kubernetes", "k8s"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch"],
    "sql": ["sql"],
    "postgresql": ["postgresql", "postgres", "psql"],
    "docker": ["docker"],
    "java": ["java"],
    "javascript": ["javascript", "js"],
    "ruby": ["ruby"],
    "react": ["react", "reactjs", "react.js"],
    "angular": ["angular", "angularjs"],
    "nodejs": ["nodejs", "node.js", "node js"],
    "graphql": ["graphql"],
    "rest": ["rest", "rest api", "restful"],
    "machine learning": ["machine learning", "ml"],
    "artificial intelligence": ["artificial intelligence", "ai"],
    "data science": ["data science"],
    "devops": ["devops", "dev ops"],
    "agile": ["agile"],
    "scrum": ["scrum"],
    "jenkins": ["jenkins", "jenkins ci", "jenkins pipelines"],
    "c++": ["c++"],
    "go": ["go", "golang", "go lang"],
    "swift": ["swift"],
    "flutter": ["flutter"],
    "vuejs": ["vue", "vuejs", "vue.js"],
    "scala": ["scala"],
    "rust": ["rust"],
    "kotlin": ["kotlin"],
    "android": ["android"],
    "ios": ["ios"],
    "spark": ["spark", "apache spark"],
    "hadoop": ["hadoop"],
    "apache kafka": ["apache kafka", "kafka"],
    "elasticsearch": ["elasticsearch", "elastic search"],
    "mongodb": ["mongodb"],
    "redis": ["redis"],
    "rabbitmq": ["rabbitmq"],
    "microservices": [
        "microservices",
        "microservices architecture",
    ],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "azure": ["azure", "microsoft azure"],
    "typescript": ["typescript", "ts"],
    "css": ["css"],
    "html": ["html"],
    "sql server": ["sql server", "mssql", "microsoft sql server"],
    "laravel": ["laravel"],
    "nextjs": ["nextjs", "next.js"],
    "nuxtjs": ["nuxtjs", "nuxt.js"],
    "swiftui": ["swiftui", "swift ui"],
    "jest": ["jest"],
    "express": ["express", "express.js", "expressjs"],
    "firebase": ["firebase"],
    "vscode": ["vscode", "vs code", "visual studio code"],
    "git": ["git"],
    "github": ["github"],
    "bitbucket": ["bitbucket"],
    "azure devops": ["azure devops"],
    "terraform": ["terraform"],
    "ansible": ["ansible", "ansible tower"],
    "puppet": ["puppet"],
    "chef": ["chef"],
    "circleci": ["circleci", "circle ci"],
    "travisci": ["travisci", "travis ci"],
    "docker compose": ["docker compose", "docker-compose"],
    "openstack": ["openstack"],
    "vagrant": ["vagrant"],
    "vmware": ["vmware"],
    "prometheus": ["prometheus"],
    "grafana": ["grafana"],
    "logstash": ["logstash"],
    "nginx": ["nginx"],
    "apache": ["apache", "apache http server"],
    "heroku": ["heroku"],
    "docker swarm": ["docker swarm"],
    "cloudformation": ["cloudformation", "aws cloudformation"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "matplotlib": ["matplotlib"],
    "seaborn": ["seaborn"],
    "scikit-learn": ["sklearn", "scikit-learn"],
    "scipy": ["scipy"],
    "opengl": ["opengl", "open gl"],
    "sqlite": ["sqlite"],
    "jupyter": ["jupyter", "jupyter notebook"],
    "mariadb": ["mariadb"],
    "flutterflow": ["flutterflow", "flutter flow"],
    "robot framework": ["robot framework"],
    "spring boot": ["spring boot"],
    "spring framework": ["spring framework"],
    "oauth": ["oauth", "oauth2", "oauth 2.0"],
    "jwt": ["jwt", "json web token"],
    "selenium": ["selenium", "selenium webdriver"],
    "puppeteer": ["puppeteer"],
    "kivy": ["kivy"],
    "grpc": ["grpc", "g-rpc"],
    "nestjs": ["nestjs", "nest.js", "nest js"],
    "apollo": ["apollo", "apollo graphql"],
    "redux": ["redux"],
    "material ui": ["material ui", "mui"],
    "storybook": ["storybook"],
    "testcafe": ["testcafe", "test cafe"],
    "meteor": ["meteor"],
    "electron": ["electron", "electron.js"],
    "ionic": ["ionic"],
    "telerik": ["telerik"],
    "jquery": ["jquery"],
    "svelte": ["svelte"],
    "tailwind css": ["tailwind css", "tailwind"],
    "figma": ["figma"],
    "webpack": ["webpack"],
    "parcel": ["parcel"],
    "gulp": ["gulp", "gulpjs"],
    "grunt": ["grunt"],
    "babel": ["babel"],
    "es6": ["es6", "ecmascript 6"],
    "pwa": ["pwa", "progressive web app"],
    "pm2": ["pm2"],
    "mongoose": ["mongoose"],
    "markdown": ["markdown"],
    "sphinx": ["sphinx"],
    "pytest": ["pytest"],
    "php": ["php"],
    "cakephp": ["cakephp"],
    "slack": ["slack"],
    "docker hub": ["docker hub"],
    "graphql subscriptions": ["graphql subscriptions"],
    "kubernetes helm": ["kubernetes helm", "helm", "helm charts"],
    "azure functions": ["azure functions"],
    "aws lambda": ["aws lambda", "lambda"],
    "google cloud functions": ["google cloud functions"],
    "fargate": ["fargate", "aws fargate", "ecs fargate"],
    "rancher": ["rancher"],
    "supertest": ["supertest"],
    "graphql resolvers": ["graphql resolvers"],
    "truffle": ["truffle"],
    "ipfs": ["ipfs"],
    "ethereum": ["ethereum"],
    "blockchain": ["blockchain"],
    "solidity": ["solidity"],
    "web3": ["web3", "web 3"],
    "webpack plugins": ["webpack plugins"],
    "neo4j": ["neo4j"],
    "neo4j cypher": ["neo4j cypher", "cypher"],
    "d3.js": ["d3.js", "d3"],
    "three.js": ["three.js", "threejs"],
    "recharts": ["recharts"],
    "rxjs": ["rxjs", "rx.js"],
    "socket.io": ["socket.io", "socket io"],
    "flask-restful": ["flask-restful", "flask restful"],
    "fastapi": ["fastapi", "fast api"],
    "serverless": ["serverless"],
    "react-native": ["react native", "react-native"],
    "dart": ["dart"],
    "event-driven architecture": [
        "event-driven architecture",
        "event driven architecture",
    ],
    "consul": ["consul"],
    "spring cloud": ["spring cloud"],
    "hbase": ["hbase"],
    "cloudwatch": ["cloudwatch", "aws cloudwatch"],
    "mongodb atlas": ["mongodb atlas"],
    "google kubernetes engine": [
        "google kubernetes engine",
        "gke",
    ],
    "istio": ["istio"],
    "confluent": ["confluent"],
    "apache flume": ["apache flume", "flume"],
    "azure kubernetes": [
        "azure kubernetes",
        "azure kubernetes service",
        "aks",
    ],
    "k8s service mesh": ["k8s service mesh", "kubernetes service mesh"],
    "k8s ingress": ["k8s ingress", "kubernetes ingress"],
    "cloud security": ["cloud security"],
    "bash": ["bash", "bash scripting", "bash commands"],
    "cloud foundry": ["cloud foundry"],
    "ci/cd": [
        "ci/cd",
        "ci cd",
        "continuous integration",
        "continuous delivery",
    ],
    "gitlab": ["gitlab"],
    "helm": ["helm", "helm charts"],
    "apache beam": ["apache beam", "beam"],
    "google data studio": ["google data studio", "looker studio"],
    "datadog": ["datadog"],
    "google analytics": ["google analytics"],
    "web scraping": ["web scraping", "web scraping"],
    "scrapy": ["scrapy"],
    "beautifulsoup": ["beautifulsoup", "beautiful soup"],
    "uikit": ["uikit", "ui kit"],
    "mongodb compass": ["mongodb compass"],
    "microfrontends": ["microfrontends", "micro frontends"],
    "ssr": ["ssr", "server-side rendering"],
    "styled components": ["styled components"],
    "mocha": ["mocha"],
    "chai": ["chai"],
    "chai assertion": ["chai assertion"],
    "docker volumes": ["docker volumes"],
    "nginx reverse proxy": ["nginx reverse proxy"],
    "kubectl": ["kubectl"],
    "aws ec2": ["aws ec2", "ec2"],
    "twilio": ["twilio"],
    "stripe": ["stripe"],
    "sendgrid": ["sendgrid"],
    "firebase": ["firebase"],
    "fastlane": ["fastlane"],
    "ecr": ["ecr", "amazon ecr", "aws ecr"],
}
